#  biocypher module settings
biocypher:

  offline: true
  head_ontology:
    url: ontology/biolink-model.owl.ttl
    root_node: entity




neo4j:

  database_name: neo4j
  wipe: true
  delimiter: '\t'
  array_delimiter: '|'
  quote_character: "'"
  skip_duplicate_nodes: true
  skip_bad_relationships: true